### PR TITLE
Use Julia v1.10

### PR DESCRIPTION
**Pull request by fivegrant**

### CODE REVIEW

**Comment by fivegrant** [comment]
@mattprintz I'd wait to merge this since the Beaker kernel expects changes to the Julia version. Once your `askem-beaker` refactor is merged, I'll open up fixes.

**Comment by mattprintz** [comment]
@fivegrant The refactor was merged last night, so I think this should be good to move forward. Anything you need me to do?

**Comment by fivegrant** [comment]
@mattprintz could the references to "1.9" be changed to "1.10" in a Beaker? I'm not 100% sure but it might have to be changed in both 'beaker-kernel' and 'askem-beaker'?

**Comment by mattprintz** [comment]
@fivegrant This should be a very minor fix, but I because of all the breakages between versions and trying to keep things in sync I'm think we should do this:
1. We cut a release (with image tag) of `askem-julia:1.9`. 
2. We update the referring repos to point to the 1.9 tag for now,
3. Merge/deploy 1.10
4. Update and test other repos as needed later on.

Good plan?

**Comment by fivegrant** [comment]
Sounds good. I'm going to copy over the GH Action for cutting releases in a separate PR in a bit

**Comment by fivegrant** [comment]
@mattprintz I tagged the `askem-julia` version here: https://github.com/DARPA-ASKEM/askem-julia/pkgs/container/askem-julia/165672475?tag=3.0.0

**Pull request merged**
